import type { Metadata } from "next";
import { Aboreto, Alice } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/navbar/navbar";
import { Footer } from "@/components/footer/footer";
import localFont from "next/font/local";
import ScrollToTopButton from "@/components/ui/scroll-to-to-bottom";
import LenisProvider from "@/components/ui/lenis-provider";

//Google Fonts
const aboreto = Aboreto({
  weight: "400",
  variable: "--font-aboreto",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const alice = Alice({
  weight: "400",
  variable: "--font-alice",
  subsets: ["latin"],
  display: "swap",
  preload: false,
});

const groovy = localFont({
  src: "../public/fonts/groovy.ttf",
  variable: "--font-groovy",
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${groovy.variable} ${aboreto.variable} ${alice.variable} antialiased`}
      >
        <ScrollToTopButton />

        <Toaster position="top-right" />
        <Navbar />
        <LenisProvider>{children}</LenisProvider>
        <Footer />
      </body>
    </html>
  );
}
